# Shell variables
# Generated by 'wal'
wallpaper='/home/deditionis/.config/wpg/wallpapers/moe0.jpg'

# Special
background='#1d1d20'
foreground='#f1ffff'
cursor='#f1ffff'

# Colors
color0='#1d1d20'
color1='#a66684'
color2='#69637d'
color3='#6981a7'
color4='#4274a9'
color5='#ba79ad'
color6='#79a1bf'
color7='#bedbf5'
color8='#34343a'
color9='#e16fa5'
color10='#796da9'
color11='#739ee3'
color12='#4391e2'
color13='#fe85e4'
color14='#85cdff'
color15='#f1ffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
