--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/deditionis/.config/wpg/wallpapers/moe0.jpg"

-- Special
background="#1d1d20"
foreground="#f1ffff"
cursor="#f1ffff"

-- Colors
color0="#1d1d20"
color1="#a66684"
color2="#69637d"
color3="#6981a7"
color4="#4274a9"
color5="#ba79ad"
color6="#79a1bf"
color7="#bedbf5"
color8="#34343a"
color9="#e16fa5"
color10="#796da9"
color11="#739ee3"
color12="#4391e2"
color13="#fe85e4"
color14="#85cdff"
color15="#f1ffff"
