--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/deditionis/.config/wpg/wallpapers/alice.jpg"

-- Special
background="#09152D"
foreground="#ffffe9"
cursor="#ffffe9"

-- Colors
color0="#09152D"
color1="#7586A2"
color2="#586395"
color3="#E7CD6D"
color4="#2E59A7"
color5="#A4A095"
color6="#3A65B3"
color7="#efe8ca"
color8="#102857"
color9="#86a9e4"
color10="#6376d1"
color11="#ffff77"
color12="#2d6fe7"
color13="#e9d9ad"
color14="#3b7ef8"
color15="#ffffe9"
