# Shell variables
# Generated by 'wal'
wallpaper='/home/deditionis/.config/wpg/wallpapers/moe2.png'

# Special
background='#0C1117'
foreground='#deffff'
cursor='#deffff'

# Colors
color0='#0C1117'
color1='#2B8DB7'
color2='#517692'
color3='#5AADC8'
color4='#206B97'
color5='#5591B0'
color6='#2CA6CA'
color7='#add9e0'
color8='#1c2938'
color9='#29bdfc'
color10='#5a9bcc'
color11='#62eaff'
color12='#1d8ed0'
color13='#5dc1f5'
color14='#29e0ff'
color15='#deffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
