# Shell variables
# Generated by 'wal'
wallpaper='/home/deditionis/.config/wpg/wallpapers/wallhaven-vgowxm.jpg'

# Special
background='#0e131e'
foreground='#fffaff'
cursor='#fffaff'

# Colors
color0='#0e131e'
color1='#9d7f82'
color2='#2f537b'
color3='#625d6e'
color4='#386998'
color5='#6376a1'
color6='#7b90bd'
color7='#cec9d5'
color8='#1d2840'
color9='#da9096'
color10='#3068a6'
color11='#786998'
color12='#3985ce'
color13='#6d8fde'
color14='#89b0ff'
color15='#fffaff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
