--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/deditionis/.config/wpg/wallpapers/moe5.jpg"

-- Special
background="#0a131f"
foreground="#fffbfd"
cursor="#fffbfd"

-- Colors
color0="#0a131f"
color1="#887C7D"
color2="#576475"
color3="#5C7289"
color4="#3D6083"
color5="#6C6C76"
color6="#758595"
color7="#c6c0c2"
color8="#152a45"
color9="#c19094"
color10="#6380a5"
color11="#6893c0"
color12="#427cb6"
color13="#7d7da8"
color14="#86acd2"
color15="#fffbfd"
